name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  who-is-tester: # id of input
    description: 'Who is tester'
    required: true
    default: 'Anna'
outputs:
  time: # id of output
    description: 'The time we greeted you'
  date: # id of output
    description: 'The date we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    - ${{ inputs.who-is-tester }}
